/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_2;


import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author Marcin
 */
public class Lab5_2 extends javax.swing.JFrame {

    /**
     * Creates new form Lab5_2
     */
    JPanel tabela;
    Container cp;
    public Lab5_2() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lewyPanel = new javax.swing.JPanel();
        producentButton = new javax.swing.JButton();
        modelButton = new javax.swing.JButton();
        typButton = new javax.swing.JButton();
        samolotButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LabelTabela = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laboratorium 5");
        setPreferredSize(new java.awt.Dimension(1300, 700));

        lewyPanel.setPreferredSize(new java.awt.Dimension(100, 600));

        producentButton.setText("producent");
        producentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producentButtonActionPerformed(evt);
            }
        });

        modelButton.setText("model");
        modelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelButtonActionPerformed(evt);
            }
        });

        typButton.setText("typ");
        typButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typButtonActionPerformed(evt);
            }
        });

        samolotButton.setText("samolot");
        samolotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samolotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lewyPanelLayout = new javax.swing.GroupLayout(lewyPanel);
        lewyPanel.setLayout(lewyPanelLayout);
        lewyPanelLayout.setHorizontalGroup(
            lewyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lewyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lewyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(producentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(samolotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lewyPanelLayout.setVerticalGroup(
            lewyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lewyPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(producentButton)
                .addGap(27, 27, 27)
                .addComponent(modelButton)
                .addGap(18, 18, 18)
                .addComponent(typButton)
                .addGap(18, 18, 18)
                .addComponent(samolotButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(lewyPanel, java.awt.BorderLayout.LINE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 100));

        LabelTabela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTabela.setText("wybierz tabelę do edycji");
        LabelTabela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(LabelTabela)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LabelTabela)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenu1.setLabel("Plik");

        jMenuItem1.setText("wyjscie");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void producentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producentButtonActionPerformed
        // TODO add your handling code here:
        cp=this.getContentPane();
        if(tabela!=null)
        {
           cp.remove(tabela);
        }
        tabela=new PanelProducent();
        cp.add(tabela);
        LabelTabela.setText("Tabela : PRODUCENT");
        this.pack();
        
    }//GEN-LAST:event_producentButtonActionPerformed

    private void modelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelButtonActionPerformed
        // TODO add your handling code here:
        cp=this.getContentPane();
        if(tabela!=null)
        {
           cp.remove(tabela);
        }
        tabela=new PanelModel();
        cp.add(tabela);
        LabelTabela.setText("Tabela : MODEL");
        this.pack();
        
    }//GEN-LAST:event_modelButtonActionPerformed

    private void typButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typButtonActionPerformed
        // TODO add your handling code here:
        cp=this.getContentPane();
        if(tabela!=null)
        {
           cp.remove(tabela);
        }
        tabela=new PanelTyp();
        cp.add(tabela);
        LabelTabela.setText("Tabela : TYP");
        this.pack();
    }//GEN-LAST:event_typButtonActionPerformed

    private void samolotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samolotButtonActionPerformed
        // TODO add your handling code here:
        cp=this.getContentPane();
        if(tabela!=null)
        {
           cp.remove(tabela);
        }
        tabela=new PanelSamolot();
        cp.add(tabela);
        LabelTabela.setText("Tabela : SAMOLOT");
        this.pack();
        this.repaint();
        
    }//GEN-LAST:event_samolotButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab5_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab5_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab5_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab5_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab5_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTabela;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lewyPanel;
    private javax.swing.JButton modelButton;
    private javax.swing.JButton producentButton;
    private javax.swing.JButton samolotButton;
    private javax.swing.JButton typButton;
    // End of variables declaration//GEN-END:variables
}
